<?php

namespace Wspot\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20200422134130 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $this->addSql("
        UPDATE custom_fields_template
            set choices = '{\"pt_br\":{\"Escola\":\"\",\"EMF ALCINO PEDRO RODRIGUES\":\"EMF ALCINO PEDRO RODRIGUES\",\"EMF ALMIRANTE TAMANDAR\u00c9\":\"EMF ALMIRANTE TAMANDAR\u00c9\",\"EMF MAMPITUBA\":\"EMF MAMPITUBA\",\"EMF PROFESSOR MANOEL FERREIRA PORTO\":\"EMF PROFESSOR MANOEL FERREIRA PORTO\",\"EMF PROFESSOR MANOEL OLIVEIRA CARNEIRO\":\"EMF PROFESSOR MANOEL OLIVEIRA CARNEIRO\",\"EMF SANTA RITA\":\"EMF SANTA RITA\",\"EMF S\u00c3O JUDAS TADEU\":\"EMF S\u00c3O JUDAS TADEU\",\"EMF ZONA SUL\":\"EMF ZONA SUL\",\"EMEI - ALCINO PEDRO RODRIGUES\":\"EMEI - ALCINO PEDRO RODRIGUES\",\"EMEI - SALINAS\":\"EMEI - SALINAS\",\"EMEI - GENTE MIÚDA\":\"EMEI - GENTE MIÚDA\",\"EMEI - PROFESSOR SADI PIPET DE OLIVEIRA\":\"EMEI - PROFESSOR SADI PIPET DE OLIVEIRA\"},\"en\":{\"School\":\"\",\"EMF ALCINO PEDRO RODRIGUES\":\"EMF ALCINO PEDRO RODRIGUES\",\"EMF ALMIRANTE TAMANDAR\u00c9\":\"EMF ALMIRANTE TAMANDAR\u00c9\",\"EMF MAMPITUBA\":\"EMF MAMPITUBA\",\"EMF PROFESSOR MANOEL FERREIRA PORTO\":\"EMF PROFESSOR MANOEL FERREIRA PORTO\",\"EMF PROFESSOR MANOEL OLIVEIRA CARNEIRO\":\"EMF PROFESSOR MANOEL OLIVEIRA CARNEIRO\",\"EMF SANTA RITA\":\"EMF SANTA RITA\",\"EMF S\u00c3O JUDAS TADEU\":\"EMF S\u00c3O JUDAS TADEU\",\"EMF ZONA SUL\":\"EMF ZONA SUL\",\"EMEI - ALCINO PEDRO RODRIGUES\":\"EMEI - ALCINO PEDRO RODRIGUES\",\"EMEI - SALINAS\":\"EMEI - SALINAS\",\"EMEI - GENTE MIÚDA\":\"EMEI - GENTE MIÚDA\",\"EMEI - PROFESSOR SADI PIPET DE OLIVEIRA\":\"EMEI - PROFESSOR SADI PIPET DE OLIVEIRA\"},\"es\":{\"Escuela\":\"\",\"EMF ALCINO PEDRO RODRIGUES\":\"EMF ALCINO PEDRO RODRIGUES\",\"EMF ALMIRANTE TAMANDAR\u00c9\":\"EMF ALMIRANTE TAMANDAR\u00c9\",\"EMF MAMPITUBA\":\"EMF MAMPITUBA\",\"EMF PROFESSOR MANOEL FERREIRA PORTO\":\"EMF PROFESSOR MANOEL FERREIRA PORTO\",\"EMF PROFESSOR MANOEL OLIVEIRA CARNEIRO\":\"EMF PROFESSOR MANOEL OLIVEIRA CARNEIRO\",\"EMF SANTA RITA\":\"EMF SANTA RITA\",\"EMF S\u00c3O JUDAS TADEU\":\"EMF S\u00c3O JUDAS TADEU\",\"EMF ZONA SUL\":\"EMF ZONA SUL\",\"EMEI - ALCINO PEDRO RODRIGUES\":\"EMEI - ALCINO PEDRO RODRIGUES\",\"EMEI - SALINAS\":\"EMEI - SALINAS\",\"EMEI - GENTE MIÚDA\":\"EMEI - GENTE MIÚDA\",\"EMEI - PROFESSOR SADI PIPET DE OLIVEIRA\":\"EMEI - PROFESSOR SADI PIPET DE OLIVEIRA\"}}'
            WHERE identifier = 'wifiescolas_school';
        ");
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        $this->addSql("
        UPDATE custom_fields_template
            set choices = '{\"pt_br\":{\"Escola\":\"\",\"EMF ALCINO PEDRO RODRIGUES\":\"EMF ALCINO PEDRO RODRIGUES\",\"EMF ALMIRANTE TAMANDAR\u00c9\":\"EMF ALMIRANTE TAMANDAR\u00c9\",\"EMF MAMPITUBA\":\"EMF MAMPITUBA\",\"EMF PROFESSOR MANOEL FERREIRA PORTO\":\"EMF PROFESSOR MANOEL FERREIRA PORTO\",\"EMF PROFESSOR MANOEL OLIVEIRA CARNEIRO\":\"EMF PROFESSOR MANOEL OLIVEIRA CARNEIRO\",\"EMF SANTA RITA\":\"EMF SANTA RITA\",\"EMF S\u00c3O JUDAS TADEU\":\"EMF S\u00c3O JUDAS TADEU\",\"EMF ZONA SUL\":\"EMF ZONA SUL\"},\"en\":{\"School\":\"\",\"EMF ALCINO PEDRO RODRIGUES\":\"EMF ALCINO PEDRO RODRIGUES\",\"EMF ALMIRANTE TAMANDAR\u00c9\":\"EMF ALMIRANTE TAMANDAR\u00c9\",\"EMF MAMPITUBA\":\"EMF MAMPITUBA\",\"EMF PROFESSOR MANOEL FERREIRA PORTO\":\"EMF PROFESSOR MANOEL FERREIRA PORTO\",\"EMF PROFESSOR MANOEL OLIVEIRA CARNEIRO\":\"EMF PROFESSOR MANOEL OLIVEIRA CARNEIRO\",\"EMF SANTA RITA\":\"EMF SANTA RITA\",\"EMF S\u00c3O JUDAS TADEU\":\"EMF S\u00c3O JUDAS TADEU\",\"EMF ZONA SUL\":\"EMF ZONA SUL\"},\"es\":{\"Escuela\":\"\",\"EMF ALCINO PEDRO RODRIGUES\":\"EMF ALCINO PEDRO RODRIGUES\",\"EMF ALMIRANTE TAMANDAR\u00c9\":\"EMF ALMIRANTE TAMANDAR\u00c9\",\"EMF MAMPITUBA\":\"EMF MAMPITUBA\",\"EMF PROFESSOR MANOEL FERREIRA PORTO\":\"EMF PROFESSOR MANOEL FERREIRA PORTO\",\"EMF PROFESSOR MANOEL OLIVEIRA CARNEIRO\":\"EMF PROFESSOR MANOEL OLIVEIRA CARNEIRO\",\"EMF SANTA RITA\":\"EMF SANTA RITA\",\"EMF S\u00c3O JUDAS TADEU\":\"EMF S\u00c3O JUDAS TADEU\",\"EMF ZONA SUL\":\"EMF ZONA SUL\"}}'
            WHERE identifier = 'wifiescolas_school';
        ");
    }
}
