<?php

namespace Wideti\DomainBundle\Repository;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPlans(){
        return $this->findAll();
    }

    public function findPlanById($id){
        return $this->find($id);
    }
}
