name: Pull Request to Master

on:
  pull_request:
    branches: [ master ]

jobs:
  test-the-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login OCIR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.OCI_REGISTRY_AUTH_URL }}
          username: ${{ secrets.OCI_REGISTRY_USER }}
          password: ${{ secrets.OCI_REGISTRY_PASSWORD }}

      - name: Test the build
        run: make build-app